#! /bin/bash
# Author    guojy
# Date      2016/08/04
# Desc      Migrate kvms from openvswitch to linux bridge

function setup_link_to_ovs()
{
    if [ ${2} == "br-wan" ];then
        port_to_ovs="wan${1}"
        sgbr="br0${1}"
    else
        if [ ${2} == "br-lan" ];then
            port_to_ovs="lan${1}"
            sgbr="br1${1}"
        else
            echo "only br-wan or br-lan allowed !"
            exit 1
        fi
    fi
    ovs-vsctl -- --if-exists del-port ${port_to_ovs} \
              -- add-port ${2} ${port_to_ovs}  \
              -- set Interface ${port_to_ovs}  type=internal \
              -- set Interface ${port_to_ovs}  external-ids:iface-status=active \
              -- set Interface ${port_to_ovs}  external-ids:iface-id=$(uuidgen)
    ip link set ${port_to_ovs} up
    brctl --help > /dev/null
    if [ $? -gt 0 ];then
        echo "bridge-util required !"
        exit 1
    fi
    [[ $(brctl show | grep ${sgbr} | wc -l) -eq 0 ]] && brctl addbr ${sgbr} || echo "bridge ${sgbr} already exists!"
    ip link set ${sgbr} up
    mac=$(virsh domiflist ${1} | grep ${2} | awk '{print $5}')
    virsh detach-interface --domain ${1} --type bridge --modle virtio --mac ${mac} --live --config
    virsh attach-interface --domain ${1} --type bridge --modle virtio --mac ${mac} --source ${sgbr} --live --config
    [[ $(brctl show | grep ${port_to_ovs} | wc -l) -eq 0 ]] && brctl addif ${sgbr} ${port_to_ovs} || \
                                                                    echo "bridge ${sgbr} already connected to ovs!"
    return 0
}

for kvm in `virsh list --all --name`;
do
    setup_link_to_ovs ${kvm}  br-wan
    setup_link_to_ovs ${kvm}  br-lan
done

